"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\
$time\n  \
[󱞪](fg:lavender) \
"""

palette = "meadow"

[palettes.meadow]
surface = '#2a2431'
poppy = '#d68583'
marigold = '#e9b17c'
sage = '#a4bba9'
cornflower = '#9cb8eb'
dew = '#84c7d5'
lavender = '#c1b0e7'

[palettes.meadow-light]
surface = '#e6e0ed'
poppy = '#9e4c4d'
marigold = '#925f2a'
sage = '#536e59'
cornflower = '#4b6697'
dew = '#2d717d'
lavender = '#6d5b90'

[directory]
format = "[](fg:surface)[ $path ]($style)[](fg:surface) "
style = "bg:surface fg:cornflower"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:surface"
symbol = " "

[git_branch]
format = "[](fg:surface)[ $symbol $branch ]($style)[](fg:surface) "
style = "bg:surface fg:dew"
symbol = ""

[git_status]
disabled = false
style = "bg:surface fg:poppy"
format = '[](fg:surface)([$all_status$ahead_behind]($style))[](fg:surface) '
up_to_date = '[ ✓ ](bg:surface fg:lavender)'
untracked = '[?\($count\)](bg:surface fg:marigold)'
stashed = '[\$](bg:surface fg:lavender)'
modified = '[!\($count\)](bg:surface fg:marigold)'
renamed = '[»\($count\)](bg:surface fg:lavender)'
deleted = '[✘\($count\)](style)'
staged = '[++\($count\)](bg:surface fg:marigold)'
ahead = '[⇡\(${count}\)](bg:surface fg:dew)'
diverged = '⇕[\[](bg:surface fg:lavender)[⇡\(${ahead_count}\)](bg:surface fg:dew)[⇣\(${behind_count}\)](bg:surface fg:sage)[\]](bg:surface fg:lavender)'
behind = '[⇣\(${count}\)](bg:surface fg:sage)'

[time]
disabled = false
format = " [](fg:surface)[ $time 󰴈 ]($style)[](fg:surface)"
style = "bg:surface fg:sage"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:surface)[ 󰧱 $user ]($style)[](fg:surface) "
show_always = true
style_root = "bg:surface fg:poppy"
style_user = "bg:surface fg:lavender"

# Languages

[c]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[elixir]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[elm]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[golang]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[haskell]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[java]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[julia]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[nodejs]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = "󰎙 "

[nim]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = "󰆥 "

[rust]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[scala]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = " "

[python]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$version ]($style)[](fg:surface)"
disabled = false
symbol = ' '

[conda]
style = "bg:surface fg:cornflower"
format = " [](fg:surface)[ $symbol$environment ]($style)[](fg:surface)"
disabled = false
symbol = '🅒 '
